### ISSUE TITLE
Chinese font problem

### ISSUE THREAD

**Issue by xingjiapeng** [MX-Linux/mx-conky-data#27]
In Chinese environment, the words in mx-conky will be Chinese.
However, the themes of conky didn't include any Chinese font, like that:
![](https://img.vim-cn.com/d5/692c8da5ce458bb30d72888c4f4e7fc98c3e08.png)
![](https://img.vim-cn.com/ce/c0ff5f6d87fd788f82a37f77e2e47504af1ee1.png)

so the words can't show up, like that:
![](https://img.vim-cn.com/7b/346ee9b2f32a8b3c964ea525281008a6f91c5f.png)

(Sorry for my awful English)

**Comment by jerry3904** [comment]
Thanks. We have not had any testing in a Chinese environment, so are very
glad to hear your results. It was our understanding that the Roboto fonts
covered that need, but that appears not to be so. Is there a font that you
suggest that we consider?

**Comment by xingjiapeng** [comment]
Hi!
I tried to edit MX-Cowon_bluw_roboto with open-source font [wqy-microhei](http://wenq.org/wqy2/index.cgi)(in package fonts-wqy-microhei), it behaves like that:
![](https://img.vim-cn.com/86/60128bbe9fd7a2dc39b16739f0e3932b963168.png)
and here is [my edit](https://paste.ubuntu.com/p/XRrkkdYx65/)

Perhaps there could be a special theme for Chinese? Thanks.

(Sorry for my awful English)

**Comment by xingjiapeng** [comment]
I thought... could the default conky setting juest use the default font of the system? Although it might not very pretty, but it will behave great and suitable for most langueages.
Thanks.

**Comment by xingjiapeng** [comment]
solved
