### ISSUE TITLE
missing build instruction

### ISSUE THREAD

**Issue by freddii** [MX-Linux/mx-conky-data#30]
I dont know how to build this package.
Is there a build instruction somewhere?

**Comment by jerry3904** [comment]
I'm not clear what you actually want.

1) if you just want the conky collection in this repo then download it using the link on the Code page.
2) if you want to use it with MX-Conky, that package is built for Debian and can be downloaded from the MX Linux repos.

**Comment by freddii** [comment]
Yes found a deb file at http://mxrepo.com/mx/repo/pool/main/m/mx-conky/mx-conky_20.4_amd64.deb
But it would still be nice to have a build-script to build my own mx-conky_*_amd64.deb

**Comment by dolphinoracle** [comment]
you just need the debhelper tool listed in the build depends in the debian
control file.  everything is there.

  the dev package tools are available in mx-packageinstaller under
Development.

**Comment by freddii** [comment]
thank you. will try that.

**Comment by freddii** [comment]
was able to build and install it with:
``
git clone https://github.com/MX-Linux/mx-conky-data
cd mx-conky-data
dpkg-buildpackage -us -uc
cd ..
sudo dpkg -i mx-conky-data_20201012mx19_all.deb
```
