### ISSUE TITLE
Weather

### ISSUE THREAD

**Issue by StanislavI22** [MX-Linux/mx-conky-data#35]
Can you pls explain how to change weather location on MX-CoreBlue? I can't figure it out, i've changed the address in acc_rcc file, but it still shows default 25 degrees. Also, the program writes this in terminal:
conky: desktop window (600017) is subwindow of root window (522)
conky: window type - desktop
conky: drawing to created window (0xa00002)
conky: drawing to double buffer
/root/.conky/nordcore/weather_raw: line 1: ?xml: No such file or directory
/root/.conky/nordcore/weather_raw: line 2: rss: No such file or directory
/root/.conky/nordcore/weather_raw: line 3: channel: No such file or directory
/root/.conky/nordcore/weather_raw: line 4: title: No such file or directory
/root/.conky/nordcore/weather_raw: line 5: link: No such file or directory
/root/.conky/nordcore/weather_raw: line 5: amp: command not found
/root/.conky/nordcore/weather_raw: line 5: /link: No such file or directory
/root/.conky/nordcore/weather_raw: line 6: $'\r': command not found
/root/.conky/nordcore/weather_raw: line 7: description: No such file or directory
/root/.conky/nordcore/weather_raw: line 7: amp: command not found
/root/.conky/nordcore/weather_raw: line 7: /description: No such file or directory
/root/.conky/nordcore/weather_raw: line 8: syntax error near unexpected token `60'
'root/.conky/nordcore/weather_raw: line 8: `		<ttl>60</ttl>
/root/.conky/nordcore/weather_raw: line 1: ?xml: No such file or directory
/root/.conky/nordcore/weather_raw: line 2: rss: No such file or directory
/root/.conky/nordcore/weather_raw: line 3: channel: No such file or directory
/root/.conky/nordcore/weather_raw: line 4: title: No such file or directory
/root/.conky/nordcore/weather_raw: line 5: amp: command not found
/root/.conky/nordcore/weather_raw: line 5: link: No such file or directory
/root/.conky/nordcore/weather_raw: line 5: /link: No such file or directory
/root/.conky/nordcore/weather_raw: line 6: $'\r': command not found
/root/.conky/nordcore/weather_raw: line 7: description: No such file or directory
/root/.conky/nordcore/weather_raw: line 7: amp: command not found
/root/.conky/nordcore/weather_raw: line 7: /description: No such file or directory
/root/.conky/nordcore/weather_raw: line 8: syntax error near unexpected token `60'
'root/.conky/nordcore/weather_raw: line 8: `		<ttl>60</ttl>

Thanks for your attention, hope you'll help me

**Comment by dolphinoracle** [comment]
you shouldn't be running the conky config has root, but as regular user.   I also not sure the weather module still works as it depended on some accuweather rss feed.   looking at the code, I think you would need to have a way to update the accuweather rss feed to your particular area.
