### ISSUE TITLE
spacing is off on new install mx23 fluxbox

### ISSUE THREAD

**Issue by ttrezren** [MX-Linux/mx-conky-data#48]
I activated ~/.conky/MX-Conkyglass/conkyt_sys_sm on a fresh install of mx fluxbox and the offsets needed tweaking to match the preview image. The font Loma isn't found in any enabled repository, so I changed it to Robot-Light and fixed the spacing. Is there a better approach? Should I submit my tweaks as a pull request? Just looking for some guidance here. -Thanks, Tim

Relevant code:
```
conky.text = [[
${alignc}${voffset 25} ${offset 35} ${font Robot-Light:size=75}${time %d}${font}${voffset -40}${offset 20}${font Robot-Light:size=30}${time %a}${voffset 40}${offset -20}${time %b}${font Robot-Light:size=75}${color2}${voffset -60}${if_match "pmfix${time %p}" == "pmfix"}${time %k:%M}${else}${time %l:%M}${endif}   ${font}${color}${template9}
##SYS##
${offset 100}${voffset -25}${font Robot-Light:size=15}${offset 80}${color1}CPU ${offset 9}${color}${cpu cpu0}%${offset 9}${color1}HDD ${offset 9}$color${fs_used_perc /}%${offset 9}${color1}RAM ${offset 9}${color}${memperc}%

]];
```

System:
```
❯ uname -a
Linux mckenzie 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux
❯ neofetch
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   tim@mckenzie 
@@@@@@@@@@@@%*+--:------=+*%@@@@@@@@@@@@   ------------ 
@@@@@@@@@#=. .-+#%@@@@@%#*+--=#@@@@@@@@@   OS: MX x86_64 
@@@@@@@+. .=%@@@@@@@@@@@@@@@@*-:+@@@@@@@   Host: iMac6,1 1.0 
@@@@@*.  *@@@@@@@@@@@@@@@@@@@@@%-.*@@@@@   Kernel: 6.1.0-28-amd64 
@@@@-  -@@@@@@@@@@@@@@@@@@@@@@@#:  -@@@@   Uptime: 7 days, 2 hours, 47 mins 
@@@:  -@@@@@@@=.*@@@@@@@@@@@@%-   = :@@@   Packages: 1882 (dpkg) 
@@=  .@@@@@@@@%- :%@@@@@@@@@+   -%@# =@@   Shell: zsh 5.9 
@%   +@@@@@@@@@@#. =@@@@@@*.  .*@@@@. %@   Resolution: 1920x1200 
@+   *@@@@@@*..*@@+  *@@%-   =@@@@@@- +@   WM: Fluxbox 
@=   *@@@@%-    -%@@- :=   -%@@@@@@@: +@   WM Theme: MX-comfort-plus-dark 
@+   :@@@=        +@@=   .#@@@@@@@@%  *@   Theme: Greybird-mx [GTK2/3] 
@%    +*.          .:     *@@#: +@@:  @@   Icons: Papirus-mxblue-darkpanes [GTK2/3] 
@@+                   :%@- :-    ::  +@@   Terminal: xfce4-terminal 
@@@-                  .=@@=         -@@@   Terminal Font: DejaVu Sans Mono 11 
@@+.                     .           +@@   CPU: Intel Core 2 T7400 (2) @ 2.167GHz 
%=..:.................::...........:..-%   GPU: NVIDIA GeForce 7300 GT 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   Memory: 1374MiB / 2968MiB 

                                                                   
                                                                   


```

**Comment by jerry3904** [comment]
This "Glass" group of conkies, which dates from well over a decade ago, seems especially sensitive to particular displays--most often the background is incorrectly adjusted to the text. I just checked the one you tried on 3 different monitors and found 3 different problems (too short horizontally or vertically). I use one (conkysys) a good deal and almost always have to adjust it. 
Changing to Roboto-Light does improve it, though the background image is still not correct. We will change both of the versions that use it, as there is a waiting list. Thanks for the report.

**Comment by ttrezren** [comment]
I also assumed it was Roboto family, but then I noticed "Robot-Light" is the spelling in the config, so I stuck with that. I didn't check to see if "Robot" family exists. It does seem that the metrics are *different* but I couldn't say better or worse specifying Roboto.
